// Generated by scripts/generateGameBalance.mts — do not edit.

pub const TICK_MICROS: i64 = 200000;
pub const TICK_DT: f64 = 0.2;

pub const STARTING_TIMBER: f64 = 160.0;
pub const STARTING_STONE: f64 = 140.0;
pub const STONE_SALVAGE_FRACTION: f64 = 0.92;
pub const TIMBER_SALVAGE_FRACTION: f64 = 0.7;
pub const RESIDENCE_TIMBER_COST: f64 = 8.0;
pub const RESIDENCE_STONE_COST: f64 = 12.0;

pub const STARTING_POPULATION: u32 = 5;
pub const POPULATION_PER_RESIDENCE: u32 = 3;
pub const RESIDENCE_POPULATION_NARROW: u32 = 2;
pub const RESIDENCE_POPULATION_WIDE: u32 = 4;
pub const NARROW_PARCEL_FRONTAGE_MAX: f64 = 9.6;
pub const WIDE_PARCEL_FRONTAGE_MIN: f64 = 14.0;
pub const RESIDENCE_FIREWOOD_CAPACITY: f64 = 40.0;
pub const RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC: f64 = 0.02;
pub const RESIDENCE_WATER_CAPACITY: f64 = 24.0;
pub const RESIDENCE_WATER_PER_PERSON_PER_SEC: f64 = 0.012;
pub const ABANDON_AFTER_DEFICIT_TICKS: u32 = 3600;
pub const RESIDENCE_RECOVERY_FIREWOOD_MIN: f64 = 8.0;
pub const RESIDENCE_RECOVERY_WATER_MIN: f64 = 5.0;
pub const RESIDENCE_SETTLE_TICKS: u32 = 250;

pub const BUILDING_ROAD_ACCESS_DISTANCE: f64 = 20.0;

pub const LODGE_TIMBER_PER_CYCLE: f64 = 3.0;
pub const LODGE_FIREWOOD_PER_CYCLE: f64 = 3.0;
pub const LODGE_DELIVERY_INTERVAL: f64 = 4.0;
pub const LODGE_FIREWOOD_PER_DELIVERY: f64 = 2.0;
pub const STONE_PER_HARVEST: f64 = 3.0;
pub const REFORESTER_REGROW_PER_SEC: f64 = 0.014;
pub const WELL_BASE_REFILL_PER_SEC: f64 = 0.42;
pub const WELL_SURGE_CHANCE_PER_TICK: f64 = 0.0022;
pub const WELL_SURGE_AMOUNT_MIN: f64 = 10.0;
pub const WELL_SURGE_AMOUNT_MAX: f64 = 26.0;
pub const WELL_SURGE_COOLDOWN_SEC: f64 = 42.0;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BuildingSimKind {
    LumberMill,
    Reforester,
    StoneQuarry,
    WoodcuttersLodge,
    Well,
}

#[derive(Clone, Copy, Debug)]
pub struct BuildingDef {
    pub kind: &'static str,
    pub cost_timber: f64,
    pub cost_stone: f64,
    pub storage_timber: f64,
    pub storage_firewood: f64,
    pub storage_stone: f64,
    pub storage_water: f64,
    pub accepts_labor: bool,
    pub max_labor: u32,
    pub work_radius: f64,
    pub action_interval: f64,
    pub pick_radius: f64,
    pub requires_road: bool,
    pub requires_mature_trees: bool,
    pub requires_quarry_stone: bool,
    pub sim_kind: Option<BuildingSimKind>,
}

const LUMBER_MILL: BuildingDef = BuildingDef {
    kind: "lumber_mill",
    cost_timber: 45.0,
    cost_stone: 15.0,
    storage_timber: 240.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    accepts_labor: true,
    max_labor: 3,
    work_radius: 210.0,
    action_interval: 9.0,
    pick_radius: 8.0,
    requires_road: true,
    requires_mature_trees: true,
    requires_quarry_stone: false,
    sim_kind: Some(BuildingSimKind::LumberMill),
};

const REFORESTER: BuildingDef = BuildingDef {
    kind: "reforester",
    cost_timber: 35.0,
    cost_stone: 10.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    accepts_labor: true,
    max_labor: 1,
    work_radius: 190.0,
    action_interval: 0.0,
    pick_radius: 8.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    sim_kind: Some(BuildingSimKind::Reforester),
};

const WOODCUTTERS_LODGE: BuildingDef = BuildingDef {
    kind: "woodcutters_lodge",
    cost_timber: 40.0,
    cost_stone: 12.0,
    storage_timber: 60.0,
    storage_firewood: 120.0,
    storage_stone: 0.0,
    storage_water: 0.0,
    accepts_labor: true,
    max_labor: 2,
    work_radius: 0.0,
    action_interval: 5.0,
    pick_radius: 8.0,
    requires_road: true,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    sim_kind: Some(BuildingSimKind::WoodcuttersLodge),
};

const STONE_QUARRY: BuildingDef = BuildingDef {
    kind: "stone_quarry",
    cost_timber: 25.0,
    cost_stone: 40.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 180.0,
    storage_water: 0.0,
    accepts_labor: true,
    max_labor: 4,
    work_radius: 55.0,
    action_interval: 9.0,
    pick_radius: 10.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: true,
    sim_kind: Some(BuildingSimKind::StoneQuarry),
};

const WELL: BuildingDef = BuildingDef {
    kind: "well",
    cost_timber: 18.0,
    cost_stone: 22.0,
    storage_timber: 0.0,
    storage_firewood: 0.0,
    storage_stone: 0.0,
    storage_water: 100.0,
    accepts_labor: false,
    max_labor: 0,
    work_radius: 90.0,
    action_interval: 0.0,
    pick_radius: 6.0,
    requires_road: false,
    requires_mature_trees: false,
    requires_quarry_stone: false,
    sim_kind: Some(BuildingSimKind::Well),
};

const ALL: &[BuildingDef] = &[LUMBER_MILL, REFORESTER, WOODCUTTERS_LODGE, STONE_QUARRY, WELL];

pub fn building_def(kind: &str) -> Option<&'static BuildingDef> {
    ALL.iter().find(|def| def.kind == kind)
}

pub fn building_def_or_err(kind: &str) -> Result<&'static BuildingDef, String> {
    building_def(kind).ok_or_else(|| format!("Unknown building kind: {kind}"))
}
