//! World seed and re-exports from generated balance data.

pub use crate::balance_generated::{
    ABANDON_AFTER_DEFICIT_TICKS, BUILDING_ROAD_ACCESS_DISTANCE, LODGE_DELIVERY_INTERVAL,
    LODGE_FIREWOOD_PER_CYCLE, LODGE_FIREWOOD_PER_DELIVERY, LODGE_TIMBER_PER_CYCLE, NARROW_PARCEL_FRONTAGE_MAX, POPULATION_PER_RESIDENCE,
    REFORESTER_REGROW_PER_SEC, RESIDENCE_FIREWOOD_CAPACITY, RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC,
    RESIDENCE_POPULATION_NARROW, RESIDENCE_POPULATION_WIDE, RESIDENCE_RECOVERY_FIREWOOD_MIN,
    RESIDENCE_SETTLE_TICKS, STONE_PER_HARVEST, TICK_DT, TICK_MICROS,
    STARTING_POPULATION, WIDE_PARCEL_FRONTAGE_MIN,
};

pub const DEFAULT_WORLD_SEED: u64 = 0x71a2e0d;
