//! World seed and re-exports from generated balance data.

pub use crate::balance_generated::{
    ABANDON_AFTER_DEFICIT_TICKS, BUILDING_ROAD_ACCESS_DISTANCE, LODGE_DELIVERY_INTERVAL,
    LODGE_FIREWOOD_PER_CYCLE, LODGE_FIREWOOD_PER_DELIVERY, LODGE_TIMBER_PER_CYCLE, NARROW_PARCEL_FRONTAGE_MAX, POPULATION_PER_RESIDENCE,
    REFORESTER_REGROW_PER_SEC, RESIDENCE_FIREWOOD_CAPACITY, RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC,
    RESIDENCE_POPULATION_NARROW, RESIDENCE_POPULATION_WIDE, RESIDENCE_RECOVERY_FIREWOOD_MIN,
    RESIDENCE_RECOVERY_WATER_MIN, RESIDENCE_SETTLE_TICKS, RESIDENCE_WATER_CAPACITY,
    RESIDENCE_WATER_PER_PERSON_PER_SEC, STONE_PER_HARVEST, TICK_DT, TICK_MICROS,
    WELL_BASE_REFILL_PER_SEC, WELL_SURGE_AMOUNT_MAX, WELL_SURGE_AMOUNT_MIN,
    WELL_SURGE_CHANCE_PER_TICK, WELL_SURGE_COOLDOWN_SEC,
    STARTING_POPULATION, WIDE_PARCEL_FRONTAGE_MIN,
};

pub const DEFAULT_WORLD_SEED: u64 = 0x71a2e0d;
