import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

type BuildingBalance = {
  label: string;
  cost: { timber: number; stone: number };
  storage: { timber: number; firewood: number; stone: number; water?: number };
  workRadius: number;
  pickRadius: number;
  harvestInterval: number;
  regrowRatePerSecond: number;
  maxLabor: number;
  acceptsLabor: boolean;
  requiresRoad: boolean;
  requiresMatureTrees: boolean;
  requiresQuarryStone: boolean;
};

type GameBalance = {
  sim: { tickMicros: number; tickDt: number };
  economy: {
    startingTimber: number;
    startingStone: number;
    stoneSalvageFraction: number;
    timberSalvageFraction: number;
    residenceTimberCost: number;
    residenceStoneCost: number;
  };
  population: {
    starting: number;
    perResidence: number;
    residencePopulationNarrow: number;
    residencePopulationWide: number;
    narrowParcelFrontageMax: number;
    wideParcelFrontageMin: number;
    residenceFirewoodCapacity: number;
    residenceFirewoodPerPersonPerSec: number;
    residenceWaterCapacity: number;
    residenceWaterPerPersonPerSec: number;
    abandonAfterDeficitTicks: number;
    residenceRecoveryFirewoodMin: number;
    residenceRecoveryWaterMin: number;
    residenceSettleTicks: number;
  };
  roads: {
    buildingRoadAccessDistance: number;
    burgageRoadFrontageDistance: number;
  };
  production: {
    lodgeTimberPerCycle: number;
    lodgeFirewoodPerCycle: number;
    lodgeDeliveryInterval: number;
    lodgeFirewoodPerDelivery: number;
    stonePerHarvest: number;
    reforesterRegrowPerSec: number;
    wellBaseRefillPerSec: number;
    wellSurgeChancePerTick: number;
    wellSurgeAmountMin: number;
    wellSurgeAmountMax: number;
    wellSurgeCooldownSec: number;
  };
  buildings: Record<string, BuildingBalance>;
};

const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(scriptDir, '..');
const balancePath = join(projectRoot, 'balance/gameBalance.json');
const balance = JSON.parse(readFileSync(balancePath, 'utf8')) as GameBalance;

const buildingKinds = Object.keys(balance.buildings);
const simKindByKind: Record<string, string | null> = {
  lumber_mill: 'LumberMill',
  reforester: 'Reforester',
  stone_quarry: 'StoneQuarry',
  woodcutters_lodge: 'WoodcuttersLodge',
  well: 'Well',
};

function rustF64(value: number): string {
  return Number.isInteger(value) ? `${value}.0` : `${value}`;
}

function generateRust(): string {
  const b = balance;
  const lines: string[] = [
    '// Generated by scripts/generateGameBalance.mts — do not edit.',
    '',
    `pub const TICK_MICROS: i64 = ${b.sim.tickMicros};`,
    `pub const TICK_DT: f64 = ${rustF64(b.sim.tickDt)};`,
    '',
    `pub const STARTING_TIMBER: f64 = ${rustF64(b.economy.startingTimber)};`,
    `pub const STARTING_STONE: f64 = ${rustF64(b.economy.startingStone)};`,
    `pub const STONE_SALVAGE_FRACTION: f64 = ${rustF64(b.economy.stoneSalvageFraction)};`,
    `pub const TIMBER_SALVAGE_FRACTION: f64 = ${rustF64(b.economy.timberSalvageFraction)};`,
    `pub const RESIDENCE_TIMBER_COST: f64 = ${rustF64(b.economy.residenceTimberCost)};`,
    `pub const RESIDENCE_STONE_COST: f64 = ${rustF64(b.economy.residenceStoneCost)};`,
    '',
    `pub const STARTING_POPULATION: u32 = ${b.population.starting};`,
    `pub const POPULATION_PER_RESIDENCE: u32 = ${b.population.perResidence};`,
    `pub const RESIDENCE_POPULATION_NARROW: u32 = ${b.population.residencePopulationNarrow};`,
    `pub const RESIDENCE_POPULATION_WIDE: u32 = ${b.population.residencePopulationWide};`,
    `pub const NARROW_PARCEL_FRONTAGE_MAX: f64 = ${rustF64(b.population.narrowParcelFrontageMax)};`,
    `pub const WIDE_PARCEL_FRONTAGE_MIN: f64 = ${rustF64(b.population.wideParcelFrontageMin)};`,
    `pub const RESIDENCE_FIREWOOD_CAPACITY: f64 = ${rustF64(b.population.residenceFirewoodCapacity)};`,
    `pub const RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC: f64 = ${rustF64(b.population.residenceFirewoodPerPersonPerSec)};`,
    `pub const RESIDENCE_WATER_CAPACITY: f64 = ${rustF64(b.population.residenceWaterCapacity)};`,
    `pub const RESIDENCE_WATER_PER_PERSON_PER_SEC: f64 = ${rustF64(b.population.residenceWaterPerPersonPerSec)};`,
    `pub const ABANDON_AFTER_DEFICIT_TICKS: u32 = ${b.population.abandonAfterDeficitTicks};`,
    `pub const RESIDENCE_RECOVERY_FIREWOOD_MIN: f64 = ${rustF64(b.population.residenceRecoveryFirewoodMin)};`,
    `pub const RESIDENCE_RECOVERY_WATER_MIN: f64 = ${rustF64(b.population.residenceRecoveryWaterMin)};`,
    `pub const RESIDENCE_SETTLE_TICKS: u32 = ${b.population.residenceSettleTicks};`,
    '',
    `pub const BUILDING_ROAD_ACCESS_DISTANCE: f64 = ${rustF64(b.roads.buildingRoadAccessDistance)};`,
    '',
    `pub const LODGE_TIMBER_PER_CYCLE: f64 = ${rustF64(b.production.lodgeTimberPerCycle)};`,
    `pub const LODGE_FIREWOOD_PER_CYCLE: f64 = ${rustF64(b.production.lodgeFirewoodPerCycle)};`,
    `pub const LODGE_DELIVERY_INTERVAL: f64 = ${rustF64(b.production.lodgeDeliveryInterval)};`,
    `pub const LODGE_FIREWOOD_PER_DELIVERY: f64 = ${rustF64(b.production.lodgeFirewoodPerDelivery)};`,
    `pub const STONE_PER_HARVEST: f64 = ${rustF64(b.production.stonePerHarvest)};`,
    `pub const REFORESTER_REGROW_PER_SEC: f64 = ${rustF64(b.production.reforesterRegrowPerSec)};`,
    `pub const WELL_BASE_REFILL_PER_SEC: f64 = ${rustF64(b.production.wellBaseRefillPerSec)};`,
    `pub const WELL_SURGE_CHANCE_PER_TICK: f64 = ${rustF64(b.production.wellSurgeChancePerTick)};`,
    `pub const WELL_SURGE_AMOUNT_MIN: f64 = ${rustF64(b.production.wellSurgeAmountMin)};`,
    `pub const WELL_SURGE_AMOUNT_MAX: f64 = ${rustF64(b.production.wellSurgeAmountMax)};`,
    `pub const WELL_SURGE_COOLDOWN_SEC: f64 = ${rustF64(b.production.wellSurgeCooldownSec)};`,
    '',
  ];

  lines.push('#[derive(Clone, Copy, Debug, PartialEq, Eq)]');
  lines.push('pub enum BuildingSimKind {');
  lines.push('    LumberMill,');
  lines.push('    Reforester,');
  lines.push('    StoneQuarry,');
  lines.push('    WoodcuttersLodge,');
  lines.push('    Well,');
  lines.push('}');
  lines.push('');
  lines.push('#[derive(Clone, Copy, Debug)]');
  lines.push('pub struct BuildingDef {');
  lines.push('    pub kind: &\'static str,');
  lines.push('    pub cost_timber: f64,');
  lines.push('    pub cost_stone: f64,');
  lines.push('    pub storage_timber: f64,');
  lines.push('    pub storage_firewood: f64,');
  lines.push('    pub storage_stone: f64,');
  lines.push('    pub storage_water: f64,');
  lines.push('    pub accepts_labor: bool,');
  lines.push('    pub max_labor: u32,');
  lines.push('    pub work_radius: f64,');
  lines.push('    pub action_interval: f64,');
  lines.push('    pub pick_radius: f64,');
  lines.push('    pub requires_road: bool,');
  lines.push('    pub requires_mature_trees: bool,');
  lines.push('    pub requires_quarry_stone: bool,');
  lines.push('    pub sim_kind: Option<BuildingSimKind>,');
  lines.push('}');
  lines.push('');

  for (const [kind, def] of Object.entries(b.buildings)) {
    const constName = kind.toUpperCase();
    const simKind = simKindByKind[kind];
    lines.push(`const ${constName}: BuildingDef = BuildingDef {`);
    lines.push(`    kind: "${kind}",`);
    lines.push(`    cost_timber: ${rustF64(def.cost.timber)},`);
    lines.push(`    cost_stone: ${rustF64(def.cost.stone)},`);
    lines.push(`    storage_timber: ${rustF64(def.storage.timber)},`);
    lines.push(`    storage_firewood: ${rustF64(def.storage.firewood)},`);
    lines.push(`    storage_stone: ${rustF64(def.storage.stone)},`);
    lines.push(`    storage_water: ${rustF64(def.storage.water ?? 0)},`);
    lines.push(`    accepts_labor: ${def.acceptsLabor},`);
    lines.push(`    max_labor: ${def.maxLabor},`);
    lines.push(`    work_radius: ${rustF64(def.workRadius)},`);
    lines.push(`    action_interval: ${rustF64(def.harvestInterval)},`);
    lines.push(`    pick_radius: ${rustF64(def.pickRadius)},`);
    lines.push(`    requires_road: ${def.requiresRoad},`);
    lines.push(`    requires_mature_trees: ${def.requiresMatureTrees},`);
    lines.push(`    requires_quarry_stone: ${def.requiresQuarryStone},`);
    lines.push(`    sim_kind: ${simKind ? `Some(BuildingSimKind::${simKind})` : 'None'},`);
    lines.push('};');
    lines.push('');
  }

  lines.push(`const ALL: &[BuildingDef] = &[${buildingKinds.map((kind) => kind.toUpperCase()).join(', ')}];`);
  lines.push('');
  lines.push('pub fn building_def(kind: &str) -> Option<&\'static BuildingDef> {');
  lines.push('    ALL.iter().find(|def| def.kind == kind)');
  lines.push('}');
  lines.push('');
  lines.push('pub fn building_def_or_err(kind: &str) -> Result<&\'static BuildingDef, String> {');
  lines.push('    building_def(kind).ok_or_else(|| format!("Unknown building kind: {kind}"))');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function generateTypeScript(): string {
  const b = balance;
  const lines: string[] = [
    '// Generated by scripts/generateGameBalance.mts — do not edit.',
    '',
    `export const BUILDING_KINDS = ${JSON.stringify(buildingKinds)} as const;`,
    'export type BuildingKind = (typeof BUILDING_KINDS)[number];',
    '',
    `export const SIM_TICK_SECONDS = ${b.sim.tickDt};`,
    '',
    `export const STARTING_TIMBER = ${b.economy.startingTimber};`,
    `export const STARTING_STONE = ${b.economy.startingStone};`,
    `export const STONE_SALVAGE_FRACTION = ${b.economy.stoneSalvageFraction};`,
    `export const TIMBER_SALVAGE_FRACTION = ${b.economy.timberSalvageFraction};`,
    `export const RESIDENCE_TIMBER_COST = ${b.economy.residenceTimberCost};`,
    `export const RESIDENCE_STONE_COST = ${b.economy.residenceStoneCost};`,
    '',
    `export const STARTING_POPULATION = ${b.population.starting};`,
    `export const POPULATION_PER_RESIDENCE = ${b.population.perResidence};`,
    `export const RESIDENCE_POPULATION_NARROW = ${b.population.residencePopulationNarrow};`,
    `export const RESIDENCE_POPULATION_WIDE = ${b.population.residencePopulationWide};`,
    `export const NARROW_PARCEL_FRONTAGE_MAX = ${b.population.narrowParcelFrontageMax};`,
    `export const WIDE_PARCEL_FRONTAGE_MIN = ${b.population.wideParcelFrontageMin};`,
    `export const RESIDENCE_FIREWOOD_CAPACITY = ${b.population.residenceFirewoodCapacity};`,
    `export const RESIDENCE_FIREWOOD_PER_PERSON_PER_SEC = ${b.population.residenceFirewoodPerPersonPerSec};`,
    `export const RESIDENCE_WATER_CAPACITY = ${b.population.residenceWaterCapacity};`,
    `export const RESIDENCE_WATER_PER_PERSON_PER_SEC = ${b.population.residenceWaterPerPersonPerSec};`,
    `export const ABANDON_AFTER_DEFICIT_TICKS = ${b.population.abandonAfterDeficitTicks};`,
    `export const RESIDENCE_RECOVERY_FIREWOOD_MIN = ${b.population.residenceRecoveryFirewoodMin};`,
    `export const RESIDENCE_RECOVERY_WATER_MIN = ${b.population.residenceRecoveryWaterMin};`,
    `export const RESIDENCE_SETTLE_TICKS = ${b.population.residenceSettleTicks};`,
    '',
    `export const BUILDING_ROAD_ACCESS_DISTANCE = ${b.roads.buildingRoadAccessDistance};`,
    `export const BURGAGE_ROAD_FRONTAGE_DISTANCE = ${b.roads.burgageRoadFrontageDistance};`,
    '',
    `export const LODGE_TIMBER_PER_CYCLE = ${b.production.lodgeTimberPerCycle};`,
    `export const LODGE_FIREWOOD_PER_CYCLE = ${b.production.lodgeFirewoodPerCycle};`,
    `export const LODGE_DELIVERY_INTERVAL = ${b.production.lodgeDeliveryInterval};`,
    `export const LODGE_FIREWOOD_PER_DELIVERY = ${b.production.lodgeFirewoodPerDelivery};`,
    `export const STONE_PER_HARVEST = ${b.production.stonePerHarvest};`,
    `export const WELL_BASE_REFILL_PER_SEC = ${b.production.wellBaseRefillPerSec};`,
    `export const WELL_SURGE_CHANCE_PER_TICK = ${b.production.wellSurgeChancePerTick};`,
    `export const WELL_SURGE_AMOUNT_MIN = ${b.production.wellSurgeAmountMin};`,
    `export const WELL_SURGE_AMOUNT_MAX = ${b.production.wellSurgeAmountMax};`,
    `export const WELL_SURGE_COOLDOWN_SEC = ${b.production.wellSurgeCooldownSec};`,
    '',
    'export type BuildingResourceCost = {',
    '  timber: number;',
    '  stone: number;',
    '};',
    '',
    'export type StorageCaps = {',
    '  timber: number;',
    '  firewood: number;',
    '  stone: number;',
    '  water?: number;',
    '};',
    '',
    'export type BuildingDefinition = {',
    '  kind: BuildingKind;',
    '  label: string;',
    '  workRadius: number;',
    '  pickRadius: number;',
    '  harvestInterval: number;',
    '  regrowRatePerSecond: number;',
    '  maxLabor: number;',
    '  acceptsLabor: boolean;',
    '};',
    '',
    `export const BUILDING_DEFINITIONS = {`,
  ];

  for (const [kind, def] of Object.entries(b.buildings)) {
    lines.push(`  ${kind}: {`);
    lines.push(`    kind: '${kind}',`);
    lines.push(`    label: ${JSON.stringify(def.label)},`);
    lines.push(`    workRadius: ${def.workRadius},`);
    lines.push(`    pickRadius: ${def.pickRadius},`);
    lines.push(`    harvestInterval: ${def.harvestInterval},`);
    lines.push(`    regrowRatePerSecond: ${def.regrowRatePerSecond},`);
    lines.push(`    maxLabor: ${def.maxLabor},`);
    lines.push(`    acceptsLabor: ${def.acceptsLabor},`);
    lines.push('  },');
  }

  lines.push('} as const satisfies Record<BuildingKind, BuildingDefinition>;');
  lines.push('');
  lines.push('export const BUILDING_COSTS = {');

  for (const [kind, def] of Object.entries(b.buildings)) {
    lines.push(`  ${kind}: { timber: ${def.cost.timber}, stone: ${def.cost.stone} },`);
  }

  lines.push('} as const satisfies Record<BuildingKind, BuildingResourceCost>;');
  lines.push('');
  lines.push('export const BUILDING_STORAGE_CAPS = {');

  for (const [kind, def] of Object.entries(b.buildings)) {
    const water = def.storage.water ?? 0;
    lines.push(
      `  ${kind}: { timber: ${def.storage.timber}, firewood: ${def.storage.firewood}, stone: ${def.storage.stone}${water > 0 ? `, water: ${water}` : ''} },`,
    );
  }

  lines.push('} as const satisfies Record<BuildingKind, StorageCaps>;');
  lines.push('');

  return lines.join('\n');
}

const rustOut = join(projectRoot, 'server/src/balance_generated.rs');
const tsOutDir = join(projectRoot, 'src/generated');
const tsOut = join(tsOutDir, 'gameBalance.ts');

writeFileSync(rustOut, generateRust());
mkdirSync(tsOutDir, { recursive: true });
writeFileSync(tsOut, generateTypeScript());

console.log(`Wrote ${rustOut}`);
console.log(`Wrote ${tsOut}`);
