import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Terrain } from '../src/terrain/Terrain.ts';
import { RiverLayout } from '../src/rivers/RiverLayout.ts';
import { RiverField } from '../src/rivers/RiverField.ts';
import { sampleHydrologyScore } from '../src/hydrology/sampleHydrology.ts';

const RESOLUTION = 128;
const scriptDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(scriptDir, '..');
const generatedDir = join(projectRoot, 'server/generated');
const jsonPath = join(generatedDir, 'hydrology_grid.json');
const rustPath = join(projectRoot, 'server/src/hydrology_grid_generated.rs');

function rustF64(value: number): string {
  return Number.isInteger(value) ? `${value}.0` : `${value}`;
}

const bounds = Terrain.fullBounds();
const riverLayout = RiverLayout.create({ bounds });
const riverField = RiverField.fromLayout({ bounds, layout: riverLayout, resolution: RESOLUTION });

const scores: number[] = [];
for (let iz = 0; iz < RESOLUTION; iz++) {
  for (let ix = 0; ix < RESOLUTION; ix++) {
    const x = bounds.minX + (ix / (RESOLUTION - 1)) * (bounds.maxX - bounds.minX);
    const z = bounds.minZ + (iz / (RESOLUTION - 1)) * (bounds.maxZ - bounds.minZ);
    scores.push(Number(sampleHydrologyScore(riverField, x, z).toFixed(4)));
  }
}

mkdirSync(generatedDir, { recursive: true });
writeFileSync(jsonPath, JSON.stringify({
  resolution: RESOLUTION,
  minX: bounds.minX,
  maxX: bounds.maxX,
  minZ: bounds.minZ,
  maxZ: bounds.maxZ,
  scores,
}, null, 2));

const rustLines = [
  '// Generated by scripts/generateHydrologyGrid.mts — do not edit.',
  '',
  `pub const HYDROLOGY_GRID_RESOLUTION: usize = ${RESOLUTION};`,
  `pub const HYDROLOGY_GRID_MIN_X: f64 = ${rustF64(bounds.minX)};`,
  `pub const HYDROLOGY_GRID_MAX_X: f64 = ${rustF64(bounds.maxX)};`,
  `pub const HYDROLOGY_GRID_MIN_Z: f64 = ${rustF64(bounds.minZ)};`,
  `pub const HYDROLOGY_GRID_MAX_Z: f64 = ${rustF64(bounds.maxZ)};`,
  '',
  `pub const HYDROLOGY_GRID_SCORES: [f32; ${scores.length}] = [`,
];

for (let i = 0; i < scores.length; i += 8) {
  const chunk = scores.slice(i, i + 8).map((score) => `${score}_f32`).join(', ');
  rustLines.push(`    ${chunk},`);
}

rustLines.push('];', '');
writeFileSync(rustPath, rustLines.join('\n'));

console.log(`Wrote ${jsonPath}`);
console.log(`Wrote ${rustPath}`);
